import { SchemaObject } from '@paljs/types'

export const schema: SchemaObject = {
  models: [
    {
      name: 'Account',
      fields: [
        {
          name: 'color',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'confirmed',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'email',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'id',
          type: 'String',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'lastSeen',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'password',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'role',
          type: 'Role',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'updatedAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'username',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'usernameLowercase',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'digits',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'rank',
          type: 'Rank',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'history',
          type: 'Result',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'maps',
          type: 'Map',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'discordLinked',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Result',
      fields: [
        {
          name: 'correct',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'corrections',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'cpm',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'id',
          type: 'String',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'incorrect',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'rawCpm',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'mode',
          type: 'Mode',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'mods',
          type: 'Mods',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'updatedAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'wordIndex',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'wpm',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'map',
          type: 'Map',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['mapId'], references: ['id'] },
        },
        {
          name: 'mapId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'account',
          type: 'Account',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['accountId'], references: ['id'] },
        },
        {
          name: 'accountId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
      ],
      documentation: '',
    },
    {
      name: 'Map',
      fields: [
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'custom',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'difficulty',
          type: 'Difficulty',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'mods',
          type: 'Mods',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'mode',
          type: 'Mode',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'enum',
          documentation: '',
          relationField: false,
        },
        {
          name: 'id',
          type: 'String',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'description',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'published',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'updatedAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'wordset',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'results',
          type: 'Result',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'creator',
          type: 'Account',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['creatorId'], references: ['id'] },
        },
        {
          name: 'creatorId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
      ],
      documentation: '',
    },
  ],
  enums: [
    { name: 'Difficulty', fields: ['EASY', 'NORMAL', 'MEDIUM', 'HARD'] },
    { name: 'Role', fields: ['USER', 'ADMIN', 'PRO', 'BETA'] },
    {
      name: 'Rank',
      fields: [
        'Novice',
        'Beginner',
        'Competent',
        'Proficient',
        'Expert',
        'Master',
      ],
    },
    { name: 'Mode', fields: ['Classic', 'Race', 'TimeAttack', 'Takedown'] },
    { name: 'Mods', fields: ['Rush', 'Perfectionist'] },
  ],
}
